namespaceOverride: ""

netatmo:
  image:
    repository: bogdaniurea/netatmo-tt-system
    tag: "0.3.0-dev"
    pullPolicy: Always

  replicaCount: 1

  service:
    port: 8000
    type: ClusterIP

monitor:
  enabled: true
  image:
    repository: bogdaniurea/netatmo-tt-monitor
    tag: "0.3.0"
    pullPolicy: Always

  replicaCount: 1

  service:
    port: 5050
    type: ClusterIP

  env:
    sourceBaseUrl: "http://netatmo-tt-system.netatmo-system.svc.cluster.local:8080"
    checkIntervalMin: 5
    checkRounds: 6
    tempDelta: 0.5
    requestTimeout: 15
    pollIntervalSeconds: 150
    valveModuleTypes: "NRV,VALVE"
    valveActiveKeys: "valve_position,valve,position,open,heating_power_request,valve_level"

mqtt:
  enabled: true
  image:
    repository: eclipse-mosquitto
    tag: "2.0.22"
    pullPolicy: IfNotPresent

  service:
    port: 1883
    type: ClusterIP

  config:
    allow_anonymous: true
    persistence: false

env:
  mqtt:
    topic: "netatmo/truetemperature"

  http:
    host: "0.0.0.0"

  global:
    frequency: "30"

  logging:
    severity: "WARNING"
    filename: "netatmo.log"

secretEnv:
  client_id: 
  client_secret: 
  username:
  password:
  home_id:
  refresh_token:
  redirect_uri: https://api.netatmo.com/oauth2/redirect
  scopes: read_thermostat write_thermostat read_smarther write_smarther
