apiVersion: v1
kind: Service
metadata:
  name: {{ include "netatmo-tt-system.fullname" . }}-monitor
  namespace: {{ default "netatmo-system" .Values.namespaceOverride }}
spec:
  type: {{ .Values.netatmo.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: 5050
      targetPort: 5050
      protocol: TCP
  selector:
    app: {{ include "netatmo-tt-system.name" . }}
    component: monitor
