apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netatmo-tt-system.fullname" . }}-mqtt
  namespace: {{ default "netatmo-system" .Values.namespaceOverride }}
  annotations:
    rollme: {{ randAlphaNum 8 | quote }}
  labels:
    app: {{ include "netatmo-tt-system.name" . }}-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "netatmo-tt-system.name" . }}-mqtt
  template:
    metadata:
      labels:
        app: {{ include "netatmo-tt-system.name" . }}-mqtt
    spec:
      containers:
      - name: mqtt
        image: "{{ .Values.mqtt.image.repository }}:{{ .Values.mqtt.image.tag }}"
        imagePullPolicy: {{ .Values.mqtt.image.pullPolicy }}
        ports:
        - name: mqtt
          containerPort: {{ .Values.mqtt.service.port }}
        volumeMounts:
        - name: mqtt-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: mqtt-config
        configMap:
          name: {{ include "netatmo-tt-system.fullname" . }}-mqtt-config