apiVersion: v1
kind: Service
metadata:
  name: {{ include "netatmo-tt-system.fullname" . }}
  namespace: {{ default "netatmo-system" .Values.namespaceOverride }}
spec:
  type: {{ .Values.netatmo.service.type }}
  ports:
  - port: {{ .Values.netatmo.service.port }}
    targetPort: {{ .Values.netatmo.service.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ include "netatmo-tt-system.name" . }}