apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netatmo-tt-system.fullname" . }}-secret
  namespace: {{ default "netatmo-system" .Values.namespaceOverride }}
type: Opaque
stringData:
  NETATMO_CREDENTIALS_CLIENT_ID: "{{ .Values.secretEnv.client_id }}"
  NETATMO_CREDENTIALS_CLIENT_SECRET: "{{ .Values.secretEnv.client_secret }}"
  NETATMO_CREDENTIALS_USERNAME: "{{ .Values.secretEnv.username }}"
  NETATMO_CREDENTIALS_PASSWORD: "{{ .Values.secretEnv.password }}"
  NETATMO_HOME_ID: "{{ .Values.secretEnv.home_id }}"
  NETATMO_CREDENTIALS_REFRESH_TOKEN: "{{ .Values.secretEnv.refresh_token }}"
  NETATMO_CREDENTIALS_SCOPES: "{{ .Values.secretEnv.scopes }}"
  NETATMO_CREDENTIALS_REDIRECT_URI: "{{ .Values.secretEnv.redirect_uri}}"
